#!/bin/sh

BRANCH=`git rev-parse --abbrev-ref HEAD`
exec < /dev/tty

echo $?;
if [ "$BRANCH" == "production"} ] || [ "$BRANCH" == "staging" ]; then
  exit 1
fi

echo
echo "[pre-commit-hook] Executing tests before Comitting."
echo "If you want to change the vars please do so in .git/hooks/pre-commit"
echo

echo "Path to homestead box ~/path/to/homestead"
read HOMESTEAD_PATH

echo "Path to application within vagrant: applicationName"
read APPLICATION_NAME

echo "Please enter the name of your homestead box. Check Homestead.yaml"
read BOX_NAME

exec vagrant ssh $BOX_NAME -c "cd $APPLICATION_NAME && vendor/bin/phpunit --configuration=tests/phpunit.xml"
exit 0
